<?php
define("LOGIN_OK",1);
define("LOGIN_FAILED",2);
define("SERVER_ERROR",3);
define("NO_ADMIN_RIGHTS",4);
define("PASSWORDS_DO_NOT_MATCH",5);
define("EMPTY_BASKET",6);
define("LOGIN_REQUIRED",7);
define("NO_LOGIN_REQUIRED",8);
define("INVALID_ID",9);

define("ACTION_OK",101);
define("ACTION_FAILED",102);

define("FORM_DATA_MISSING",103);
define("INVALID_USER_NAME",104);
define("INVALID_USER_ID",105);
define("INVALID_PASS",106);
define("INVALID_EMAIL",107);
define("USER_NOT_FOUND",108);
define("USER_NAME_ALREADY_EXISTS",109);
define("USER_ID_ALREADY_EXISTS",110);
define("USER_EMAIL_ALREADY_EXISTS",111);
define("INVALID_ADDRESS",112);

define("ROWS_ON_PAGE",5);
?>